# config.yaml
model: 'xgboost'

lags: [1, 2, 3, 6, 12, 13, 14, 24, 25, 26, 48, 49, 72, 168]
rolling_avgs: [1, 3, 9, 24, 48, 72, 86, 168]
delta_reference_points:
  - [1, 2]
  - [1, 3]
  - [1, 6]
  - [1, 24]
  - [24, 25]
  - [48, 49]
  - [169, 1]
  - [168, 169]
std_windows: [3, 6, 12, 24, 48, 72, 86, 168]
num_zeros_windows: [6, 12, 24]
hour_shifts: [0, 6, 12, 18]
weekday_shifts: [0, 3, 6]
push_all_lags_by: 0

use_station_id_feat: True
use_cell_id_feat: True
use_beam_id_feat: True

train_percentage: 0.6
val_percentage: 0.3
run_shap: false
target_df_names: ['thp_vol', 'mr_number']
feat_base_df_names: ['thp_vol', 'mr_number']

xgb_hyperparams:
  objective: 'reg:squarederror'
  eval_metric: 'mae'
  eta: 0.015
  gamma: 2.8
  max_depth: 15
  subsample: 0.7
  early_stopping_rounds: 15
  n_estimators: 600
  enable_categorical: True
